---
- name: move build directory to releases directory
  shell: "mv {{ build_path }} {{ release_path }}"

- name: update the current symlink to most recent release
  file:
    src: "{{ release_path }}"
    dest: "{{ current_path }}"
    state: "link"
    force: "yes"

- name: cleanup old releases
  shell: "ls -1d [0-9]* | sort -rn | tail -n $((`ls -1d [0-9]* | sort -rn | wc -l` > {{ keep_releases }} ? `ls -1d [0-9]* | sort -rn | wc -l` - {{ keep_releases }} : 0)) | xargs rm -rf {}"
  when: cleanup
